<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsOhMyBotPlugin>true</IsOhMyBotPlugin>
        <PluginName>ImageConverter</PluginName>
        <AssemblyName>OhMyBot.Plugins.ImageConverter</AssemblyName>
        <RootNamespace>OhMyBot.Plugins.ImageConverter</RootNamespace>
    </PropertyGroup>

</Project>
